# Setup
title:        CometVisu
tagline:      The CometVisu open source development project for a building automation visualisation (e.g. KNX or OpenHAB)
baseurl:      ""

# About/contact
author:
  name:       Christian Mayer and the CometVisu contributers
  url:        http://test.cometvisu.org

# Gems
gems:
#  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown
permalink: /news/:year/:month/:day/:title

#paginate: 5
#paginate_path: "/news/page:num/"

# Translations
t:
  en:
    tagline: "The CometVisu open source development project for a building automation visualisation (e.g. KNX or OpenHAB)"
    about:
      name: "About"
      url: "/about"
    news:
      name: "News"
      url: "/news"
    gallery:
      name: "Screenshots"
      url: "/screenshots"
    manual:
      name: "Manual"
      url: "http://test.cometvisu.org/CometVisu/de/manual/"
    apidoc:
      name: "API Documentation"
      url: "http://test.cometvisu.org/CometVisu/api/"
  de:
    tagline: "Das CometVisu Open Source Projekt für eine Visualisierung für Gebäudeautomatisierung (z.B. KNX oder OpenHAB)"
    about:
      name: "Impressum"
      url: "/about.de"
    news:
      name: "Neuigkeiten"
      url: "/news/index.de"
    gallery:
      name: "Screenshots"
      url: "/screenshots.de"
    manual:
      name: "Handbuch"
      url: "http://test.cometvisu.org/CometVisu/de/manual/"
    apidoc:
      name: "API Dokumentation"
      url: "http://test.cometvisu.org/CometVisu/api/"
      
# Collections - screenshot
collections:
  screenshotFiles:
    descriptions:
      - dir: "0.9.1"
        title: 
          en: "Release 0.9.1"
          de: "Release 0.9.1"
      - dir: "0.9.0"
        title:
          en: "Release 0.9.0"
          de: "Release 0.9.0"
      - dir: "0.8.5"
        title: 
          en: "Release 0.8.5"
          de: "Release 0.8.5"
      - dir: ""
        title: 
          en: "Others"
          de: "Andere"
    text:
      imageAofB:
        en: "Image %1 of %2"
        de: "Bild %1 von %2"