# Setup
title:        CometVisu
tagline:      The CometVisu open source development project for a building automation visualisation (e.g. KNX or OpenHAB)
# Note: baseurl must be the "subdirectory" for the pages, like "CometVisu"
#       for "http://test.cometvisu.org/CometVisu".
#       As this page is on the top level the baseurl must stay empty,
#       cf. http://blog.parkermoore.de/2014/04/27/clearing-up-confusion-around-baseurl/
url:          https://www.cometvisu.org
baseurl:      
manualurl:    https://www.cometvisu.org/CometVisu

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata

#Others
markdown: kramdown
kramdown:
  hard_wrap: false
permalink: /news/:year/:month/:day/:title

# jekyll-github-metadata data:
#repository: CometVisu/CometVisu
repository: CometVisu/cometvisu.github.io

#paginate: 5
#paginate_path: "/news/page:num/"

# Translations
t:
  en:
    locale: en_GB
    tagline: "The CometVisu open source development project for a building automation visualisation (e.g. KNX or OpenHAB)"
    index:
      url: "/"
      name: "The smart home visualisation"
    features:
      name: "Features"
      url: "/features"
    about:
      name: "About"
      url: "/about"
    news:
      name: "News"
      url: "/news"
    gallery:
      name: "Screenshots"
      url: "/screenshots"
    demo:
      name: "Demo"
      url: "https://www.cometvisu.org/CometVisu/de/latest/demo/"
    development:
      name: "Development"
      url: "/development"
    manual:
      name: "Manual"
      url: "https://www.cometvisu.org/CometVisu/en/latest/manual/"
    apidoc:
      name: "API Documentation"
      url: "https://www.cometvisu.org/CometVisu/en/current/api/"
    languageSelect: "Language select"
    generatedOn: "Generated on"
    license:
      pageExplain: "Except where otherwise noted, content on this site is licensed under a"
      pageType: "Creative Commons Attribution 4.0 International license"
      codeExplain: "The CometVisu code is licensed under the GPLv3"
    latestNews: "Latest news:"
    maintainedBy: "is maintained by"
    author: "Christian Mayer and the CometVisu contributers"
    commits: "commits"
  de:
    locale: de_DE
    tagline: "Das CometVisu Open Source Projekt für eine Visualisierung für Gebäudeautomatisierung (z.B. KNX oder OpenHAB)"
    index:
      name: "Die Smart Home Visualisierung"
      url: "/index.de"
    features:
      name: "Facts &amp; Features"
      url: "/features.de"
    about:
      name: "Impressum / Datenschutz"
      url: "/about.de"
    news:
      name: "Neuigkeiten"
      url: "/news/index.de"
    gallery:
      name: "Screenshots"
      url: "/screenshots.de"
    demo:
      name: "Demo"
      url: "https://www.cometvisu.org/CometVisu/de/latest/demo/"
    development:
      name: "Entwicklung"
      url: "/development.de"
    manual:
      name: "Handbuch"
      url: "https://www.cometvisu.org/CometVisu/de/latest/manual/"
    apidoc:
      name: "API Dokumentation"
      url: "https://www.cometvisu.org/CometVisu/en/current/api/"
    languageSelect: "Sprachwahl"
    generatedOn: "Erzeugt am"
    license:
      pageExplain: "Wo nicht anders ausgewiesen steht diese Seite unter der"
      pageType: "Creative Commons Attribution 4.0 International Lizenz"
      codeExplain: "Der CometVisu Code steht unter der GPLv3 Lizenz"
    latestNews: "Letzte Neuigkeiten:"
    maintainedBy: "wird gepflegt durch"
    author: "Christian Mayer und alle Beitragende der CometVisu"
    commits: "Beiträge"
      
# Collections - screenshot
collections:
  screenshotFiles:
    descriptions:
      - dir: "0.10.0"
        title: 
          en: "Release 0.10.0 (Mar 5, 2017)"
          de: "Release 0.10.0 (5. März 2017)"
      - dir: "0.9.1"
        title: 
          en: "Release 0.9.1 (Mar 13, 2016)"
          de: "Release 0.9.1 (13. März 2016)"
      - dir: "0.9.0"
        title:
          en: "Release 0.9.0 (Nov 1, 2015)"
          de: "Release 0.9.0 (1. November 2015)"
      - dir: "0.8.5"
        title: 
          en: "Release 0.8.5 (Jan 14, 2015)"
          de: "Release 0.8.5 (14. Januar 2015)"
      - dir: "0.8.0"
        title: 
          en: "Release 0.8.0 (Nov 17, 2013)"
          de: "Release 0.8.0 (17. November 2013)"
      - dir: "0.6.0"
        title: 
          en: "Release 0.6.0"
          de: "Release 0.6.0"
      - dir: ""
        title: 
          en: "Others"
          de: "Andere"
    text:
      imageAofB:
        en: "Image %1 of %2"
        de: "Bild %1 von %2"
