# Setup
title:        CometVisu
tagline:      The CometVisu open source development project for a building automation visualisation (e.g. KNX or OpenHAB)
baseurl:      ""
paginate:     1

# About/contact
author:
name:         Christian Mayer and the CometVisu contributers
url:          http://test.cometvisu.org

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown
permalink: /news/:year/:month/:day/:title
