# Setup
title:        CometVisu
tagline:      The CometVisu open source development project for a building automation visualisation (e.g. KNX or OpenHAB)
baseurl:      ""
paginate:     1

# About/contact
author:       Christian Mayer and the CometVisu contributers
name:         Christian Mayer and the CometVisu contributers
url:          http://test.cometvisu.org

# SEO
facebook:
  publisher:  https://www.facebook.com/CometVisu/

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

#Others
markdown: kramdown
permalink: /news/:year/:month/:day/:title

paginate: 5
paginate_path: "/news/page:num/"

# Translations
t:
  en:
    about:
      name: "About"
      url: "/about/"
  de:
    about:
      name: "Impressum"
      url: "/about.de/"